name: Java Build and Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile Java Code with javac
      run: |
        mkdir -p bin  # Crea la carpeta bin
        javac -d bin *.java  # Compila los archivos .java en la raíz

    - name: Checkstyle Analysis
      run: |
        java -jar checkstyle-8.45-all.jar -c /google_checks.xml src > checkstyle-result.txt || true
        cat checkstyle-result.txt

    - name: SpotBugs Analysis
      run: |
        wget https://repo1.maven.org/maven2/com/google/code/spotbugs/spotbugs/4.6.1/spotbugs-4.6.1.jar  # URL actualizada
        java -jar spotbugs-4.6.1.jar -textui -output spotbugs-result.xml -auxclasspath bin src/**/*.java
        cat spotbugs-result.xml

    - name: JaCoCo Code Coverage
      run: |
        wget https://github.com/jacoco/jacoco/releases/download/v0.8.8/jacoco-0.8.8.zip
        unzip jacoco-0.8.8.zip
        java -jar jacoco-0.8.8/lib/jacocoant.jar report build/jacoco.exec --classfiles bin --sourcefiles src --html report
        cat report/index.html


