name: Java Checkstyle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compilar código Java
      run: |
        mkdir -p bin  # Crear carpeta de compilados
        javac -d bin *.java  # Compilar archivos .java en la raíz

    - name: Descargar Checkstyle
      run: |
        wget -O checkstyle.jar https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.4/checkstyle-10.12.4-all.jar

    - name: Ejecutar Checkstyle
      run: |
        java -jar checkstyle.jar -c /google_checks.xml *.java || true

