name: Java CI with Checkstyle, SpotBugs, and JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Paso 3: Instalar dependencias y compilar el proyecto
      - name: Compile project
        run: |
          mkdir -p target
          javac -d target $(find . -name "*.java")

      # Paso 4: Ejecutar Checkstyle
      - name: Run Checkstyle
        run: java -cp target checkstyle.Main -c /google_checks.xml $(find . -name "*.java")

      # Paso 5: Ejecutar SpotBugs
      - name: Run SpotBugs
        run: java -jar spotbugs-all.jar -textui -output target/spotbugs $(find . -name "*.class")

      # Paso 6: Ejecutar JaCoCo y generar reporte
      - name: Run JaCoCo
        run: |
          java -javaagent:jacocoagent.jar -cp target <YourTestClass> > result.log

