name: Java Build, Check, and Analyze

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Instalar JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Crear el directorio bin para los archivos compilados si no existe
    - name: Create bin directory
      run: mkdir -p bin

    # Compilar el código fuente con javac
    - name: Compile Java code
      run: |
        javac -d bin Inventory.java OrderManager.java StudentManager.java TaskManager.java

    # Ejecutar Checkstyle
    - name: Run Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.42/checkstyle-8.42-all.jar -P /tmp
        java -jar /tmp/checkstyle-8.42-all.jar -c /google_checks.xml Inventory.java OrderManager.java StudentManager.java TaskManager.java

    # Ejecutar SpotBugs
    - name: Run SpotBugs
      run: |
        wget https://github.com/spotbugs/spotbugs/releases/download/spotbugs-4.7.0/spotbugs-4.7.0.zip -P /tmp
        unzip /tmp/spotbugs-4.7.0.zip -d /tmp
        java -jar /tmp/spotbugs-4.7.0/lib/spotbugs.jar -textui -output spotbugs-report.txt bin

    # Ejecutar JaCoCo (incluir cobertura de pruebas)
    - name: Run JaCoCo
      run: |
        mkdir -p jacoco-reports
        javac -d bin -cp .:path-to-your-test-classes -sourcepath . Inventory.java OrderManager.java StudentManager.java TaskManager.java
        java -javaagent:/path/to/jacocoagent.jar -cp bin com.example.Inventory
        mv jacoco.exec jacoco-reports/
        java -cp jacoco-reports -jar /path/to/jacoco-cli.jar report jacoco-reports/jacoco.exec --classfiles bin --html jacoco-reports

    # Subir el informe de JaCoCo como artefacto
    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: jacoco-reports/

    # Subir el informe de SpotBugs
    - name: Upload SpotBugs report
      uses: actions/upload-artifact@v4
      with:
        name: spotbugs-report
        path: spotbugs-report.txt

    # Subir el informe de Checkstyle
    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: checkstyle-report.xml
