name: Java CI with JaCoCo and Checkstyle

on:
  push:
    branches:
      - master   # Puedes cambiar esta rama a la que uses en tu proyecto
  pull_request:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest   # Usar un runner de Ubuntu para la ejecución

    steps:
    # Paso 1: Hacer checkout del repositorio
    - name: Check out repository
      uses: actions/checkout@v2

    # Paso 2: Configurar JDK 11
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    # Paso 3: Crear directorios necesarios
    - name: Create bin directory
      run: mkdir -p bin

    # Paso 4: Descargar el agente JaCoCo
    - name: Download JaCoCo agent
      run: wget https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.8/org.jacoco.agent-0.8.8.jar -P /tmp

    # Paso 5: Descargar el CLI de JaCoCo
    - name: Download JaCoCo CLI
      run: wget https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/0.8.8/org.jacoco.cli-0.8.8.jar -P /tmp

    # Paso 6: Descargar Checkstyle
    - name: Download Checkstyle
      run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.45/checkstyle-8.45-all.jar -P /tmp

    # Paso 7: Compilar el código Java
    - name: Compile Java code
      run: javac -d bin Inventory.java OrderManager.java StudentManager.java TaskManager.java

    # Paso 8: Ejecutar Checkstyle
    - name: Run Checkstyle
      run: java -jar /tmp/checkstyle-8.45-all.jar -c /google_checks.xml src/

    # Paso 9: Ejecutar el programa con el agente JaCoCo
    - name: Run JaCoCo with agent
      run: java -javaagent:/tmp/org.jacoco.agent-0.8.8.jar -cp bin com.example.Inventory

    # Paso 10: Mover el archivo jacoco.exec generado
    - name: Move jacoco.exec
      run: mv jacoco.exec jacoco-reports/

    # Paso 11: Generar el informe de cobertura de JaCoCo en formato HTML
    - name: Generate JaCoCo report
      run: java -cp /tmp/org.jacoco.cli-0.8.8.jar org.jacoco.cli.internal.Main report jacoco-reports/jacoco.exec --classfiles bin --html jacoco-reports
