name: Java Build, Check, and Analyze

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    # Instalar JDK 11 de Temurin
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'   # Agregar este parámetro

    # Crear el directorio bin para los archivos compilados si no existe
    - name: Create bin directory
      run: mkdir -p bin

    # Compilar el código fuente con javac
    - name: Compile Java code
      run: |
        javac -d bin Inventory.java OrderManager.java StudentManager.java TaskManager.java

    # Ejecutar Checkstyle
    - name: Run Checkstyle
      run: |
        wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.42/checkstyle-8.42-all.jar -P /tmp
        java -jar /tmp/checkstyle-8.42-all.jar -c /google_checks.xml Inventory.java OrderManager.java StudentManager.java TaskManager.java

    # Ejecutar JaCoCo (incluir cobertura de pruebas)
    - name: Run JaCoCo
      run: |
        # Crear directorios necesarios
        mkdir -p jacoco-reports

        # Descargar JaCoCo (agente)
        wget https://github.com/jacoco/jacoco/releases/download/v0.8.8/jacoco-0.8.8-agent.jar -P /tmp

        # Compilar el código y las pruebas
        javac -d bin -cp .:path-to-your-test-classes -sourcepath . Inventory.java OrderManager.java StudentManager.java TaskManager.java

        # Ejecutar el programa con el agente JaCoCo
        java -javaagent:/tmp/jacoco-0.8.8-agent.jar -cp bin com.example.Inventory

        # Mover el archivo jacoco.exec generado
        mv jacoco.exec jacoco-reports/

        # Generar el informe de cobertura de JaCoCo en formato HTML
        wget https://github.com/jacoco/jacoco/releases/download/v0.8.8/jacoco-0.8.8-cli.jar -P /tmp
        java -cp /tmp/jacoco-0.8.8-cli.jar org.jacoco.cli.internal.Main report jacoco-reports/jacoco.exec --classfiles bin --html jacoco-reports

    # Subir el informe de JaCoCo como artefacto
    - name: Upload JaCoCo report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: jacoco-reports/

    # Subir el informe de Checkstyle
    - name: Upload Checkstyle report
      uses: actions/upload-artifact@v4
      with:
        name: checkstyle-report
        path: checkstyle-report.xml
