name: Java CI with Checkstyle, SpotBugs, and JaCoCo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Java
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: ./mvnw install -DskipTests

      # Paso 4: Ejecutar Checkstyle
      - name: Run Checkstyle
        run: ./mvnw checkstyle:checkstyle

      # Paso 5: Ejecutar SpotBugs
      - name: Run SpotBugs
        run: ./mvnw spotbugs:check

      # Paso 6: Ejecutar JaCoCo y generar reporte
      - name: Run JaCoCo and generate report
        run: ./mvnw clean verify

      # Paso 7: Subir los reportes a GitHub Pages (opcional, si quieres visualizar los reportes)
      - name: Upload Checkstyle report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/checkstyle
          publish_branch: gh-pages

      - name: Upload SpotBugs report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/spotbugs
          publish_branch: gh-pages
